### ISSUE TITLE
Add more camera settings 

### ISSUE THREAD

**Issue by thbl** [mainsail-crew/mainsail#1033]
### Requested feature:

Add v4l2-ctl settings to mainsail like this octoprint plugin https://github.com/The-EG/OctoPrint-CameraSettings

### Solves the following problem:

More control of camera settings like brightness and exposure, could give better image quality.

**Comment by thbl** [comment]
would also make it possible to control PTZ web cameras

**Comment by meteyou** [comment]
there have to be more/better support in crowsnest or moonraker for it, but it would be possible. i added it to vNext, so we will check it in the future to implement it. thx for your request.

**Comment by simonvez** [comment]
hi.. has this been implemented ? :)

**Comment by meteyou** [comment]
@simonvez atm you can only use the crowsnest config to add v4l2-ctl settings

**Comment by meteyou** [comment]
Because Mainsail is only a web interface and has no part on the host itself to control a camera, I close this FR until there is a software part on the raspberry pi/host that can do this and we can communicate with it.

If someone finds a way/software, please post it here and I will reactivate this FR.
