### ISSUE TITLE
[FR] Add a drop-down list to change the active extruder at the RETRACT/EXTRUDE section

### ISSUE THREAD

**Issue by naikymen** [mainsail-crew/mainsail#1207]
### Requested feature:

Add a drop-down list of extruders that triggers an appropriate ACTIVATE_EXTRUDER command when an extruder is selected on the drop-down list.

Currently this exists for presssure-advance, but **not** for the EXTRUDE/RETRACT buttons below.

![image](https://user-images.githubusercontent.com/3259326/209227410-d8b5536c-0acb-40ea-9393-16374f387c8c.png)

### Solves the following problem:

The "pressure advance" settings respond to the drop-down list, however the EXTRUDE/RETRACT buttons respond to the active stepper (which does not change when the extruder in the existing list changes).

This behaviour is unexpected and confusing.

There is no way of moving a secondary extruder from Mainsail without defining undocumented/obscure macros.

### Additional information:

See: https://github.com/mainsail-crew/mainsail/issues/1206

For comparison, selecting a different extruder in Fluidd actually changes the extruder. Which is of course the most intuitive behaviour.

![image](https://user-images.githubusercontent.com/3259326/209226858-437e0e31-7fae-4e15-9ef8-50527e50991b.png)

**Comment by meteyou** [comment]
we decided against activate_extruder because this is only an internal command. most systems need several commands to change the extruder and the correct gcode command for this is T0, T1, Tx. If you have a system with multi extruder, you also need these macros. otherwise you can't even print multicolour. (exception superslicer, which has decided against the standard).
