### ISSUE TITLE
G-code viewer artifacts

### ISSUE THREAD

**Issue by Matszwe02** [mainsail-crew/mainsail#1237]
### Mainsail Version:

v2.4.1

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Duplicated layers visible on prints in gcode viewer. Tested on Firefox and Opera

![image](https://user-images.githubusercontent.com/49353902/213279776-808596e9-e78b-4f8b-8fcc-b2fe2ad8444b.png)

### What did you expect to happen instead?

Normal rendering

### How to reproduce this bug?

It happens from time to time as I try to view 3d models. MainsailOS on RPI 4 (CM4), freshly updated all packages. Slicer Cura 5

**Comment by meteyou** [comment]
please upload this gcode

**Comment by meteyou** [comment]
But you must make the bug report in the gcode viewer. Mainsail, use this library: https://github.com/Sindarius/npm_gcodeviewer

**Comment by Matszwe02** [comment]
[3DBenchy.zip](https://github.com/mainsail-crew/mainsail/files/10451228/3DBenchy.zip)

**Comment by Sindarius** [comment]
I'll look into correcting this issue in the viewer. However, what is happening is your make blob g-code `G1 Z4 E40 F50 ; make blob` makes the viewer believe that that is the initial layer height because it's the first extrusion of that layer. So when it goes to render your first layer it is oversized. 

With the blob line
![image](https://user-images.githubusercontent.com/12520045/213474100-597a3326-bc28-468f-b492-ee31de796fe3.png)

Without
![image](https://user-images.githubusercontent.com/12520045/213474138-4e829779-656b-4e0d-a500-5a76b46eba19.png)

**Comment by Sindarius** [comment]
This PR includes a fix for this issue. https://github.com/mainsail-crew/mainsail/pull/1239

**Comment by Matszwe02** [comment]
Thanks @Sindarius for spotting the issue!
