### ISSUE TITLE
Desktop notification

### ISSUE THREAD

**Issue by koonweee** [mainsail-crew/mainsail#1267]
### Requested feature:

The ability to turn on desktop notifications to notify on certain printer states would be great! (eg. print completion etc)

### Additional information:

I'm not super familiar with Vue, but I think this is the relevant API https://developer.mozilla.org/en-US/docs/Web/API/notification. Happy to take a look at implementation and do a PR if this is a wanted feature :)

**Comment by meteyou** [comment]
Thanks for your request, but I think this will not work. The first requirement for notifications like this would be HTTPS.

But feel free to test it and make a PR. It would be nice to have some features like that. Maybe you can combine it with Moonraker notify component so that the user can create customize notifications: https://moonraker.readthedocs.io/en/latest/configuration/#notifier
