### ISSUE TITLE
Option toggle for „manual probe calibration window“

### ISSUE THREAD

**Issue by Staubgeborener** [mainsail-crew/mainsail#1310]
### Requested feature:

It would be a good feature, if the user can enable or disable the manual probe calibration window in option menu with a toggle switch.

### Solves the following problem:

Doing a `PROBE_CALIBRATE` there is this “new” probe calibration windows (released in [version 2.4.0](https://github.com/mainsail-crew/mainsail/pull/1077)) which helps to adjust the probe. I would love to do this by my own with the good old `TESTZ Z=` command.

### Additional information:

Maybe the same procedure for `SCREWS_TILT_CALCULATE` command,

**Comment by ColonelPanic-42** [comment]
Please merge the fix for this. I don't know who asked for the "helper" dialogs but I for one consider it an anti-feature. I used to be able to go back and forward between my PC and printer to tune with `SCREWS_TILT_CALCULATE` and just hit the up arrow and enter to retrigger the command, but now there's an extra step to move the mouse and click the "Accept" button to clear the modal to get back to the main UI again each time. The modal provides _no_ extra benefit that the console and just makes for an extra interaction.
