### ISSUE TITLE
Shutdown GCode

### ISSUE THREAD

**Issue by leitenky** [mainsail-crew/mainsail#1395]
### Requested feature:

Add the ability to run a user defined G-Code before shutting down host. This could be  integrated into the Host Shutdown item in the power/restart menu in the top right of the user interface, or allow the creation of a new item in the power menu 

### Solves the following problem:

When Shutting down host, other items can be turned off such as Fans, LEDs Ect, Beeps emitted ect

**Comment by meteyou** [comment]
I think that Mainsail is the wrong place for this function. Mainsail is just a GUI. It doesn't execute the shutdown command itself.

It just sends an API request to Moonraker for the shutdown. Furthermore, I see gcode in general as a problem in this use case because it will only be executed when klipper is running. Since I can't really check in mainsail if these are already executed or not. I only got back from the API an "ok, the command was queued."

But in general, you have a thought error. When you shut down the host, the MCU loses the connection to Klippy (the Klipper software part on the SBC). In this case, the MCU firmware switch to shutdown, and all values are set to the shutdown value. This means all heater_fan or controller_fan are set to 100% (if there is no other setting in the config). So this function will not fit in your use case.

Just my 2 cents

**Comment by leitenky** [comment]
Hi thanks for the feedback.  Basically what I'm trying to do is when I do a shutdown, I want the LEDs and chamber lights, and the chamber fan to stop.  
Is there something I might be missing that would ensure those all shutdown then the host shuts down? 
I currently have a gcode that shuts those items off then calls to shutdown the host, I just don't know how I could place it in the power menu.

**Comment by meteyou** [comment]
This is the "Shutdown" state of your board. This should be a "safety function". In this state, all heaters should be off and all fans which should protect your hardware will be on 100%. This is quite normal, because your Host is shutdown and cannot control your hardware.

You have 2 options:
- Shut down your hardware also
- don't shutdown your SBC

PS: If you need help to setup anything, pls use the #support-forum on the Mainsail Discord. The issue tracker is not for help.
