### ISSUE TITLE
WebCam does not work in public network using  any port other than 80

### ISSUE THREAD

**Issue by zch6348135** [mainsail-crew/mainsail#1406]
### Mainsail Version:

v2.5.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

WebCam works well in LAN network,but it doesn't work in public network. The port mapping function of the router is used.
Normal url is : http://xxxxxx.f3322.net:19980/fonts/roboto-light.woff2.
webcam url is :http://xxxxxx.f3322.net/webcam/?action=snapshot&bypassCache=xxxx

### What did you expect to happen instead?

To be able to see the camera stream in pubic network

### How to reproduce this bug?

Convert port 80 to other

**Comment by meteyou** [comment]
This is quite normal because the mainsail instance has nothing to do with the webcam URL. Just use absolute paths to fix it. We changed this behavior in a previous version, and there were only issues. So I won't fix this issue for view users to create another issue for many users.

PS: If you check the issue tracker, the same question comes up again every two months...
