### ISSUE TITLE
Make SET_PIN work even when Klippy is not running

### ISSUE THREAD

**Issue by RobusTetus** [mainsail-crew/mainsail#1541]
### Requested feature:

It would be great if the SET_PIN command for RPi GPIO pins would work even when Klippy is not running, or the mcu board is not powered on.

### Solves the following problem:

I finished the upgrading of my ender 3 v2 and I added a relay to switch on/off power to the mcu board. Essentially to make it partially autonomous - I wanted the printer to turn itself off after like 30 minutes after it finishes printing. Mainly because I have the printer in the same room as I sleep so it is better for me to not think about getting up and turning it off manually when it can be easily done with a relay.

**Comment by meteyou** [comment]
Mainsail is only a web interface with no direct access to your hardware because it only runs in your browser on your client.

SET_PIN is a Klipper command and is only available when Klipper is running. But for your use case, Moonraker has a separate solution that is fully supported by Mainsail. Moonraker is full-time available and has hardware access on your pi/host.

 Here are the docs from Moonraker power devices: https://moonraker.readthedocs.io/en/latest/configuration/#power
