### ISSUE TITLE
Z_ENDSTOP_CALIBRATE Values of - and -- are the same

### ISSUE THREAD

**Issue by menthol1979** [mainsail-crew/mainsail#1729]
### Mainsail Version:

2.9.1

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

When I tried to calibrate the Z_ENDSTOP of my Voron V0.2, I noticed that the - and -- buttons move exactly the same amount of 0.200

### What did you expect to happen instead?

I think - would be 0.100 and -- 0.200

### How to reproduce this bug?

Observed in the Z_ENDSTOP_CALIBRATE popup window

**Comment by meteyou** [comment]
Thx for your report, but this bug is no Mainsail Bug. Mainsail only send the command `test-` or `test--`. The size of this steps are calculated in Klipper itself. but something like that is quite normal, because you only get different sizes, when you change the direction and then it will be the half, but at the beginning its quite normal.
