### ISSUE TITLE
First boot on a RPi 3 B v1.2 results in kernel panic

### ISSUE THREAD

**Issue by Ergonomicmike** [mainsail-crew/mainsail#1739]
### Mainsail Version:

2.9.1

### Browser:

Other (Please tell us below)

### Device:

Other (Please tell us below)

### Operating System:

Other (Please tell us below)

### What happened?

Thanks for trying to make installation of Mainsail easy.
I tried installing the latest Mainsail on my Pi 3 Model B, V1.2, 2015, per your instructions at mainsail.xyz.
No success. Resulted in a kernal panic early on during First Boot.
So then I re-downloaded the same image on the same SD card and put it in my Pi 2.
That booted and eventually resulted in a command prompt. (On an HDMI monitor.)
Your instructions say to perform First Boot with the Pi hooked up to the printer. But other video tutorials show first boot with a stand-alone Pi.
I'm not a Linux geek. But from a high level standpoint, I don't understand why having a printer hooked up matters at First Boot, where the file system is being expanded.
In any event, trying First Boot on my Pi 3 Model B didn't complete even when hooked up to my printer.
I'm going to guess that either there is something wrong with my Pi 3 Model B, or that the mainsail image doesn't work with my V1.2.
It's not important. This Linux stuff is too hard for me. And I only have an Ender 3 v2.
But thought that I would mention it, in case it's an issue on your end.

### What did you expect to happen instead?

It should have completed to the command line, as the image did on my RPi 2.

### How to reproduce this bug?

Try installing on a RPi 3 B v1.2 I suppose. (Unless it's a hardware problem at my end.)

### Additional information:

I'm not good a linux, so except for physically writing down the last line on the screen at the kernel panic (or taking a photograph of the screen) I can't help much.

**Comment by meteyou** [comment]
Thanks for your report, but you mixed up many things. At first, Mainsail is not the same as MainsailOS. Mainsail (this repo here) is only the web interface. Nothing more. MainsailOS is a preinstalled image for Raspberry Pi and some other SBCs. so you mixed up the repo for the report.

The Raspberry Pi image is based on a normal Raspberry Pi OS lite. We only add all software parts. So if it would not boot on any Rpi 3B v1.2, no Rpi 3B v1.2 would boot with the official Raspberry image. The current image has also been downloaded 144.5k times so far. If there had been such a serious problem, a few more users would have already reported it.

This sentence is only in the guide because users have seen that a cable was missing and have been messing around with the RPI during the first boot-up until the power plug was pulled out, and that broke the image.

Next time you make a bug report, please add the exact version (image version) and post a photo of the error message. Furthermore, the whole screen is important and not just the last line.

**Comment by Ergonomicmike** [comment]
Thanks. Sorry.
