### ISSUE TITLE
Feature request - Fan Alias

### ISSUE THREAD

**Issue by dfbpurcell** [mainsail-crew/mainsail#2005]
### Requested feature:

It would be great to be able to assign an alias to the pins in the miscellaneous tab. I renamed them in the printer.cfg, which renames them in the mainsail interface but they are still referenced elsewhere whether it be in gcode or in the printer files im not sure. And I'm too stupid to figure out how to fix it. This means they no longer work when printing if you rename them. 
![image](https://github.com/user-attachments/assets/141e3e88-eac8-4b76-b902-1e893d2ee246)

### Solves the following problem:

Allows you to name the pins without messing up the functionality. Avoids confusion between fans, allows for easy remote control without having to go back and forth to see if you activated the right fan.

**Comment by meteyou** [comment]
Thank you very much for your feature request, but unfortunately, I have to reject it. one of our main principles is that the hardware in Mainsail is named exactly as in the config, making it easier to find the corresponding config. This question is being asked more often, but only in connection with current new vendor printers (mostly Creality k1). Here, the vendors should provide clean configurations. When I see your screenshot above, I notice several incorrect configurations here (all output_pin modules instead of LEDs or fans).

But if you want to clean/fix your config and need help, please join our Discord server or open a post in the discussions area here on GitHub.
