### ISSUE TITLE
Feature Request: ETA until PAUSE / Color Change

### ISSUE THREAD

**Issue by Naeaeaeaeae** [mainsail-crew/mainsail#2099]
### Requested feature:

The estimates (like the until end of print) for an defined event like PAUSE or COLOR Change.

Therefore there can be a better planning for multi step printing.

### Solves the following problem:

![grafik](https://github.com/user-attachments/assets/1d8341a4-991e-4ccb-b56a-5d339323d149)

something like that, just a seperate line with one more date. Maybe if you hover, then there will be some explination

### Additional information:

Knowing when the print is going to pause without a notification is a nice feature

**Comment by meteyou** [comment]
Thank you for your feature request!

Unfortunately, this is not possible at the moment because Mainsail does not have access to the G-code and therefore does not know if or when a `PAUSE` or `M600` command is included in the G-code.

One possible approach for such a feature would be to preprocess the G-code (similar to the `exclude_object` feature). This could define the relevant timestamps for events like PAUSE or color changes at the start of the G-code and store them in Klipper. These timestamps could then be read and displayed by Mainsail.

However, this would first require changes to Klipper and Moonraker before we could even begin implementing this in Mainsail. For now, I’ll close this feature request, as the issue tracker serves as our to-do list. If there is any progress on the other components, please link it here and reopen this request.
