### ISSUE TITLE
[FR] Add HLS stream support

### ISSUE THREAD

**Issue by geNAZt** [mainsail-crew/mainsail#387]
**Is your feature request related to a problem? Please describe.**
Sort of. On my Raspberry PI 4 when using a mjpeg webcam (which is default) it caps the network port and its nearly unuseable (via SSH for example). Also this setup will never work over the network (like on mobile over the internet).

**Describe the solution you'd like**
I would like a webcam type added which loads the HLS polyfill for the video HTML5 tag ( https://github.com/video-dev/hls.js/ ). This would allow to have restreamer (for example) configured to provide a HLS encoded stream from the webcam (in my case C920) hardware encoder for h264 to HLS.

**Describe alternatives you've considered**
Reducing the JPG quality to the bandwidth limitations of my mobile device which resulted in a blob of squares. Also i reduced the resolution from 1080 to 720p which reduces quality even on my local network.

**Additional context**

**Comment by KwadFan** [comment]
Hello geNAZt,
first of all, thank you for your Request. We are working currently on a new 'webcamd'.
This will have multiple Streamtypes available.
mjpeg is an kinda outdatet format but since we are limited in Hardware Resources, we have to do some further test to get the best out of it. If you are interested to take a look in the WIP Repo, but I have to say it is a really early stage there are several things missing where I am working on.
If you use a MainsailOS 0.5.0 Image you can take a look at it.
Install instructions are in the README.md. Basicly it replaces the now used webcamd.
The whole Documentation is missing, unfortunatly you are a bit on your own at this stage.
Used Streamservices are mjpg_streamer ( for compatibilty reasons ), ustreamer and v4l2rtspserver.
Last named is capable of rtsp, hls, mpeg4-dash.
A webrtc service is also planned but not implemented yet.
Please take a look at the Repo of the named streamservices.

Here we go:
[crowsnest](https://github.com/KwadFan/webcamtest)
[v4l2rtspserver](https://github.com/mpromonet/v4l2rtspserver)
[ustreamer](https://github.com/pikvm/ustreamer)

Regards

**Comment by lixxbox** [comment]
We are working on a way to integrate a webcam stream via WebRTC in our side project "crowsnest". In our tests we found that the latency is much lower than HLS.

Unfortunately, the feature is dependent on Crowsnest, which is why I set the status to "blocked" for now. We will keep you up to date.

**Comment by leigh-johnson** [comment]
:wave: Hey folks, creator of [PrintNanny.ai](https://printnanny.ai/) here - I'd like to contribute to getting HLS working in Mainsail. 

For context, PrintNanny runs a WebRTC stack with HLS as a compatibility fallback. I strongly prefer hardware-accelerated h264 encoding to JPEG, since PrintNanny runs computationally-expensive computer vision tasks on the Raspberry Pi - every optimization matters!

I'm happy to propose a PR to get the conversation started. =)

**Comment by meteyou** [comment]
Hey @leigh-johnson! I sent you a private message via discord to not give false hope too soon in public.

**Comment by meteyou** [comment]
this FR is fixed with this PR: https://github.com/mainsail-crew/mainsail/pull/1258
