### ISSUE TITLE
[FR] Clear console button

### ISSUE THREAD

**Issue by rlaferla** [mainsail-crew/mainsail#658]
**Is your feature request related to a problem? Please describe.**
There are at times, too many console entries but I don't want to restart apps.  For example, I may be doing resonance testing and I just want to clear past entries so I can focus on the output from the ADXL.  There are many other cases.

**Describe the solution you'd like**
A button and/or command to clear the console.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by th33xitus** [comment]
That is actually something i considered usefull just a few weeks ago. It would be best if this would be integrated into Moonraker first. If we just empty the history in Mainsail, a refresh of the page would bring the entries back, because the console history is served my Moonraker. So Moonraker needs a function like this in the first place.

**Comment by th33xitus** [comment]
https://github.com/mainsail-crew/mainsail/pull/672
