### ISSUE TITLE
[feature request] Home XY button 

### ISSUE THREAD

**Issue by LazaroFilm** [mainsail-crew/mainsail#729]
### Requested feature:

A [🏠 XY] button next to the [🏠All] button in the Controls section

### Solves the following problem:

On my Core XY with PP Orion probe, I sometimes need to home XY first before homing Z. I could Home X then Home Y, but that's two clicks, and it drops the bed twice. It seems like there is plenty of room for a orange Home XY button at the top.

**Comment by th33xitus** [comment]
> I **_sometimes_** need to home XY first before homing Z

The thing is, that features like that, that people only rarely use ( keyword "sometimes" ) are hard to integrate in existing layouts in terms of of UX/UI. And since we have 3 different styles of controls, it even makes it harder. So we always need to come up with solutions for all 3 styles as it would be a bad job if different control styles have different feature sets. What might be easy to integrate in one control style, might be a lot harder in another style. In some cases it even would make more sense to write a homing overwrite and just execute that which then, at best, covers 100% of situations so that there is no "sometimes" involved at all.

Which control style are we speaking about btw?
